# Generated by Django 5.0.14 on 2026-09-24 03:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=20, unique=True, verbose_name='Número de cuenta')),
                ('titular', models.CharField(max_length=100, verbose_name='Titular')),
                ('rut', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Ingrese un RUT válido. Ejemplo: 12.345.678-9', regex='^\\d{1,2}\\.?\\d{3}\\.?\\d{3}-[\\dkK]$')], verbose_name='RUT')),
                ('tipo_cuenta', models.CharField(choices=[('VISTA', 'Cuenta Vista'), ('CORRIENTE', 'Cuenta Corriente'), ('AHORRO', 'Cuenta de Ahorro')], max_length=20, verbose_name='Tipo de cuenta')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('fecha_apertura', models.DateField(default=datetime.date.today, verbose_name='Fecha de apertura')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('BLOQUEADA', 'Bloqueada'), ('CERRADA', 'Cerrada')], default='ACTIVA', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cuenta bancaria',
                'verbose_name_plural': 'Cuentas bancarias',
                'ordering': ['numero_cuenta'],
            },
        ),
    ]
