# Generated by Django 5.0.14 on 2026-09-24 03:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='sueldo_mensual',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sueldo mensual'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='numero_cuenta',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True, verbose_name='Número de cuenta'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='tipo_cuenta',
            field=models.CharField(choices=[('DEBITO', 'Cuenta Débito'), ('CORRIENTE', 'Cuenta Corriente'), ('CREDITO', 'Cuenta con línea de crédito')], max_length=20, verbose_name='Tipo de cuenta'),
        ),
    ]
