# Generated by Django 5.0.14 on 2026-09-24 04:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_cuentabancaria_sueldo_mensual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancaria',
            name='rut',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Ingrese un RUT válido. Ejemplo: 12.345.678-5', regex='^\\d{1,2}\\.?\\d{3}\\.?\\d{3}-[\\dkK]$')], verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo disponible'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='sueldo_mensual',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Renta mensual'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='tipo_cuenta',
            field=models.CharField(choices=[('DEBITO', 'Cuenta Débito'), ('CORRIENTE', 'Cuenta Corriente')], max_length=20, verbose_name='Producto solicitado'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='titular',
            field=models.CharField(max_length=100, verbose_name='Nombre completo'),
        ),
    ]
