# Generated by Django 5.0.14 on 2026-09-24 04:50

import cuentas.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_alter_cuentabancaria_rut_alter_cuentabancaria_saldo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='telefono',
            field=models.CharField(default='900000000', max_length=9, validators=[django.core.validators.RegexValidator(message='Ingrese un celular chileno válido de 9 dígitos. Ejemplo: 912345678', regex='^9\\d{8}$')], verbose_name='Teléfono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='correo',
            field=models.EmailField(max_length=150, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[cuentas.models.validar_rut_chileno], verbose_name='RUT'),
        ),
    ]
