# Generated by Django 5.0.14 on 2026-09-24 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_cuentabancaria_telefono_alter_cuentabancaria_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancaria',
            name='saldo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo disponible'),
        ),
    ]
