# Generated by Django 5.0.14 on 2026-09-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_alter_cuentabancaria_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='tarjeta_credito_solicitada',
            field=models.BooleanField(default=False, verbose_name='Tarjeta de crédito solicitada'),
        ),
    ]
