# Generated by Django 5.0.14 on 2026-10-07 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_cuentabancaria_tarjeta_credito_solicitada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_bancaria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
