# Generated by Django 5.0.14 on 2026-10-08 02:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_cuentabancaria_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancaria',
            name='correo',
            field=models.EmailField(max_length=60, unique=True, validators=[django.core.validators.MaxLengthValidator(60, message='El correo no puede superar los 60 caracteres.')], verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='sueldo_mensual',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='La renta mensual no puede ser negativa.'), django.core.validators.MaxValueValidator(Decimal('50000000'), message='La renta mensual no puede superar los $50.000.000 CLP.')], verbose_name='Renta mensual'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='titular',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, message='El nombre debe tener al menos 3 caracteres.'), django.core.validators.MaxLengthValidator(50, message='El nombre no puede exceder los 50 caracteres.'), django.core.validators.RegexValidator(message='El nombre solo debe contener letras y espacios.', regex="^[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ\\s'-]+$")], verbose_name='Nombre completo'),
        ),
    ]
